server:
  port: 4040
spring:
  profiles:
    active: dev
  application:
    name: draw-service
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html; charset=utf-8

---
# idea测试环境
spring:
  profiles: dev
  rabbitmq:
    port: 5672
    host: localhost
    username: springcloud
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    custom:
      appid: 9A064E7A180BB4790F827F546F699CC3
      exchange: draw-exchange
      routingkey: draw-routing
      queue: draw-queue
liumapp:
  filemanager:
    savePath: /usr/local/tomcat/project/draw-signature-area/data/



